# *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*
# *  CLASS input parameter file  *
# *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

# This example of input file, intended for CLASS beginners, lists only
# the most common input parameters with small comments. Only lines
# containing an equal sign not preceded by a sharp sign "#" are considered by
# the code, any other line is considered as a comment.
#
# The normal syntax is:      parameter = value(s)


# -------------------------
# ----> General parameters:
# -------------------------

# REQUESTED OUTPUT FROM CLASS (Important!)
#  - 'tCl' for temperature Cls,
#  - 'pCl' for polarization (TE,BB,EE) Cls,
#  - 'lCl' for CMB lensing POTENTIAL Cl (Cl^psi-psi, required for lensed Cls),
#  - 'nCl' (or 'dCl') for density number count Cls,
#  - 'sCl' for galaxy lensing potential Cls (Cl^phi-phi),
#  - 'mPk' for total matter power spectrum P(k),
#  - 'dTk' for density transfer functions,
#  - 'vTk' for velocity transfer functions,
#  - 'Sd' for spectral distortions
#        --> deflection d: Cl^dd = l(l+1) C_l^phi-phi
#        --> convergence kappa and shear gamma: the share the same harmonic
#            power spectrum: Cl^gamma-gamma = 1/4 * [(l+2)!/(l-2)!] C_l^phi-phi
output = tCl,pCl,lCl,mPk

P_k_max_h/Mpc = 1.                # Maximum k for P(k) in 1/Mpc

# ----------------------------
# ----> Cosmological parameters:
# ----------------------------

h = 0.67810                       # Dimensionless reduced Hubble parameter (H_0 / (100km/s/Mpc))
omega_b = 0.02238280              # Reduced baryon density (Omega*h^2)
omega_cdm = 0.1201075             # Reduced cold dark matter density (Omega*h^2)

# If you have respectively 0,1,2, or 3 MASSIVE neutrinos and the default T_ncdm of 0.71611,
# designed to give M_tot/omega_nu of 93.14 eV, and if you want N_eff equal to 3.044,
# then you should pass for N_ur 3.044,2.0308,1.0176, or 0.00441
N_ur = 0.00441                    # Effective number of MASSLESS neutrino species

N_ncdm = 1                        # Massive neutrino species
m_ncdm = 0.02                     # Mass of the massive neutrinos
T_ncdm = 0.71611                  # Massive neutrino temperature in units of photon temperature
deg_ncdm = 3                      # Degeneracy of massive neutrinos

# ----------------------------
# ----> Thermodynamics/Heating parameters:
# ----------------------------

tau_reio = 0.05430842             # Optical depth of reionization

# ----------------------------
# ----> Primordial parameters:
# ----------------------------

k_pivot = 0.05                    # Pivot scale for A_s,n_s
ln10^{10}A_s = 3.0980             # ln Amplitude of prim spectrum
n_s = 0.9660499                   # Spectrum tilt

# ----------------------------------
# ----> Decay parameters:
# ----------------------------------

Gamma_yp = 1.0e8                  # Decay rate of the Y particle in units of 1/Mpc     
maxyr_yp = 0.07                   # Maximum value of rho_Y/rho_r
f_yp = 0.6                        # Fraction of the decaying particle’s energy transferred to photons

# -------------------------
# ----> Precision parameters:
# -------------------------

# Chosen to ensure that all perturbation modes
# are initialized well before Y decay becomes significant,
# and that the TCA is disabled immediately after
# the integration of each perturbation mode begins.

gauge = synchronous
start_small_k_at_tau_c_over_tau_h = 1.e-9
start_large_k_at_tau_h_over_tau_k = 0.05
start_large_k_at_gamma_y_over_h = 1.e-4
tight_coupling_trigger_tau_c_over_tau_h = 1.1e-9
tight_coupling_trigger_tau_c_over_tau_k = 1.e-10
tight_coupling_trigger_gamma_y_over_h = 1.1e-4

# ----------------------------------
# ----> Output parameters:
# ----------------------------------

overwrite_root = no               # Overwrite the output files?
write_background = no             # Write background parameter table
write_thermodynamics = no         # Write thermodynamics parameter table
write_primordial = no             # Write primordial parameter table
write_parameters = yes            # Write used/unused parameter files
write_warnings = yes              # Warn about forgotten/wrong inputs

#Verbosity
input_verbose = 1
background_verbose = 4
thermodynamics_verbose = 4
perturbations_verbose = 1
transfer_verbose = 1
primordial_verbose = 1
harmonic_verbose = 1
fourier_verbose = 1
lensing_verbose = 1
output_verbose = 1
